find_package(Vulkan REQUIRED)
if (NOT VULKAN_FOUND)
    message(FATAL_ERROR "Vulkan installation required")
endif ()
find_package(VulkanMemoryAllocator CONFIG REQUIRED)
find_package(VulkanMemoryAllocator-Hpp CONFIG REQUIRED)
find_package(vk-bootstrap CONFIG REQUIRED)
find_package(spirv_cross_core REQUIRED)
include("${CMAKE_CURRENT_LIST_DIR}/avaTargets.cmake")